```{r}
# manually set the 16*16 matrix for the base model
h <- 0.5033415
r1 <- 0.63
r2 <- 1.2
s1 <- 0.34
s2 <- 0.71
A1 <- c(r1, r1, r2, r2,r2,r2,r2,r2,r2,r2,r2,r2,r2,r2,r2,r2)
A2 <- rep(0, times = 16)
A2[1] <- s1
A3 <- rep(0, times = 16)
A3[2] <- s2
A4 <- rep(0, times = 16)
A4[3] <- s2
A5 <- rep(0, times = 16)
A5[4] <- s2
A6 <- rep(0, times = 16)
A6[5] <- s2
A7 <- rep(0, times = 16)
A7[6] <- s2
A8 <- rep(0, times = 16)
A8[7] <- s2
A9 <- rep(0, times = 16)
A9[8] <- s2
A10 <- rep(0, times = 16)
A10[9] <- s2
A11 <- rep(0, times = 16)
A11[10] <- s2
A12 <- rep(0, times = 16)
A12[11] <- s2
A13 <- rep(0, times = 16)
A13[12] <- s2
A14 <- rep(0, times = 16)
A14[13] <- s2
A15 <- rep(0, times = 16)
A15[14] <- s2
A16 <- rep(0, times = 16)
A16[15] <- s2
combined <- rbind(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16)
parameter_matrix <- matrix(combined, nrow = 16, ncol = 16)

for (i in 3:16) {
  parameter_matrix[i,i] <- -h
}
parameter_matrix


eigen(parameter_matrix)
eigen(parameter_matrix)$values[1]
```

```{r}
h <- 0.5033415
r1 <- 0.6
r2 <- 1.15
s1 <- 0.32
s2 <- 0.68
A1 <- c(r1, r1, r2, r2,r2,r2,r2,r2,r2,r2,r2,r2,r2,r2,r2,r2)
A2 <- rep(0, times = 16)
A2[1] <- s1
A3 <- rep(0, times = 16)
A3[2] <- s2
A4 <- rep(0, times = 16)
A4[3] <- s2
A5 <- rep(0, times = 16)
A5[4] <- s2
A6 <- rep(0, times = 16)
A6[5] <- s2
A7 <- rep(0, times = 16)
A7[6] <- s2
A8 <- rep(0, times = 16)
A8[7] <- s2
A9 <- rep(0, times = 16)
A9[8] <- s2
A10 <- rep(0, times = 16)
A10[9] <- s2
A11 <- rep(0, times = 16)
A11[10] <- s2
A12 <- rep(0, times = 16)
A12[11] <- s2
A13 <- rep(0, times = 16)
A13[12] <- s2
A14 <- rep(0, times = 16)
A14[13] <- s2
A15 <- rep(0, times = 16)
A15[14] <- s2
A16 <- rep(0, times = 16)
A16[15] <- s2
combined <- rbind(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16)
parameter_matrix <- matrix(combined, nrow = 16, ncol = 16)

for (i in 3:16) {
  parameter_matrix[i,i] <- -h
}
parameter_matrix


eigen(parameter_matrix)
eigen(parameter_matrix)$values[1]
```



```{r}

# calculate eigenvalues of the parameter matrix
eigen(parameter_matrix)
eigen(parameter_matrix)$values[1]
```


```{r}
# best case parameters
r1 <- 0.63
r2 <- 1.2
s1 <- 0.34
s2 <- 0.71
c <- 5
h <- 0.7

t <- seq(1, 16, by =1)
population <- matrix(rep(NA, times = 16*length(t)), ncol = length(t), nrow = 16)
# row: age level
# col: time

# set inital value
population[1,1] <- 10 # initial value of age 1
for (i in 2:16) {
  population[i,1] <- 0
}

# calculate population at each time step
for (i in 2:length(t)) {
  population[1,i] <- r1*sum(population[1:2, i-1]) + r2*sum(population[3:16, i-1]) + c
  population[2,i] <- s1*population[1,i-1] +c 
  for (j in 3:4) {
    population[j,i] <- s2*population[j-1,i-1] -h*population[j, i-1]
  }
  for (j in 5:16) {
    population[j,i] <- s2*population[j-1,i-1] -h*population[j, i-1]
  }
}

population <- as.data.frame(population)


plot(t, population[1,], type = "l", col = 1, ylim = c(0,250))
for (i in 2:16) {
  lines(t, population[i,], col =i)
}
#legend("right", legend = c("A1", "A2", "A3","A4","A5","A6","A7","A8","A9","A10","A11","A12","A13","A14", "A15", "A16"),
       #col = seq(1,16,1), lwd=1)
```


```{r}
# best case parameters
r1 <- 0.6
r2 <- 1.15
s1 <- 0.32
s2 <- 0.68

t <- seq(1, 25, by =1)
population <- matrix(rep(NA, times = 16*length(t)), ncol = length(t), nrow = 16)
# row: age level
# col: time

# set initial value
population[1,1] <- 5 # initial value of age 1
for (i in 2:16) {
  population[i,1] <- 5
}
for (i in 2:length(t)) {
  population[1,i] <- r1*sum(population[1:2, i-1]) + r2*sum(population[3:16, i-1])
  population[2,i] <- s1*population[1,i-1]
  for (j in 3:16) {
    population[j,i] <- s2*population[j-1,i-1]
  }
}
plot(t, population[1,], type = "l", ylim = c(0, 3000))
for (i in 2:16) {
  lines(t, population[i,], col = i)
}
```

```{r}

```






















